line-length = 79
src = ["src"]
include = ["src/**.py", "tests/**.py"]
exclude = ["src/dishka/_adaptix/**"]

lint.select = [
    "E",
    "F",
    "BLE",
    "B",
    "COM",
    "C4",
    "ERA",
    "T20",
    "I",
    "N",
    "ASYNC",
    "PIE",
    "RUF",
]


[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"